### ISSUE TITLE
Expected 'Page' but found COSName{ExtGState}

### ISSUE THREAD

**Issue by JamoCA** [mjclemente/pdfbox.cfc#2]
When extracting text from 3rd party PDFs, I came across this error (pdfbox.cfc; line 47):

```
java.lang.IllegalStateException: Expected 'Page' but found COSName{ExtGState} at
org.apache.pdfbox.pdmodel.PDPageTree.sanitizeType(PDPageTree.java:250) at
org.apache.pdfbox.pdmodel.PDPageTree.access$300(PDPageTree.java:41) at
org.apache.pdfbox.pdmodel.PDPageTree$PageIterator.next(PDPageTree.java:210) at
org.apache.pdfbox.pdmodel.PDPageTree$PageIterator.next(PDPageTree.java:170) at
org.apache.pdfbox.text.PDFTextStripper.processPages(PDFTextStripper.java:320) at
org.apache.pdfbox.text.PDFTextStripper.writeText(PDFTextStripper.java:272) at
org.apache.pdfbox.text.PDFTextStripper.getText(PDFTextStripper.java:233) at
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at
...
```

NOTE: I'm not sure which PDF caused this error yet.  (We use automation to bulk process new PDF files returned from a client's very large Dropbox folder using the API.)

I found this Apache Jira post potentially regarding the same error:
https://issues.apache.org/jira/browse/PDFBOX-4019

I was wondering how you'd want to handle this error?  Use try/catch and return an empty string?

**Comment by mjclemente** [comment]
Thanks for the report - I'll take a look!

Thanks for tracking down the Jira post - looks like they have an example PDF there that I should be able to use for testing.

As you suggest, I think that since it's an issue with the PDF itself, a try/catch is the appropriate solution for handling it.

**Comment by mjclemente** [comment]
Ok - using the PDF from that Jira issue I was able to recreate the issue. The fix wraps it in a try/catch and logs the error to stderr, returning an empty string.

**Comment by JamoCA** [comment]
Thanks! I've updated it on our ACF2016 server.  _(Unrelated Issue: I noticed that I was using `pdfbox-app-2.0.21.jar` and `xmpbox-2.0.21.jar` without any issues. The current release is 2.0.25. I tried it and it doesn't work.)_

**Comment by mjclemente** [comment]
re 2.0.25 - updating for the latest version is on my todo list!

First putting some tests in place so that I can automate that type of update and track down the issues faster.

**Comment by mjclemente** [comment]
Alrighty - I think I've got the latest release working with 2.0.25 if you want to give it a try. Feel free to create an issue if you run into any problems. Cheers!
