### ISSUE TITLE
Recommend using cfformat

### ISSUE THREAD

**Issue by homestar9** [mjclemente/pdfbox.cfc#3]
Hey Matt!
This PDFbox module is awesome! I was actually playing around with PDF manipulation myself when I stumbled upon your module.  Rather than re-inventing the wheel, I'm going to fork your project and add the functionality I have been playing with.  Specifically, I have been working on a way to extract pages as images (like cfpdf action=thumbnail).  If I can get it working, I'll submit a PR to your repo.  

One suggestion I have is to run `cfformat` on the code when building Forgebox/Coldbox modules. It ensures that the indentation follows Ortus' standards and makes it easier for others to contribute.   It will have the added benefit of making sure that when someone submits a PR, you won't see a hundred different file changes when indentation shifts around between contributors.

**Comment by homestar9** [comment]
I apologize! I realized you do have a .cfformat.json file but it threw me off because the indentation looked different in this repo from the other Ortus ones I have contributed to.  Feel free to ignore my previous post.

**Comment by mjclemente** [comment]
Ahh, yeah. I've only recently started using the .cfformat.json file. Right now it's tailored to my preferences, though I'm still fiddling a bit to find what I think works best.

Sorry for any confusion, and glad you've found the project helpful!

**Comment by homestar9** [comment]
I created a [new branch in my fork](https://github.com/homestar9/pdfbox.cfc/tree/feature/createImages) of the project.  My goal was to give the module the ability to create images from pages (a feature Lucee no longer has since version 5).  

I also made cbjavaloader a dependency, which may or may not fall in line with your goals for the project.  My idea was that I didn't want users to have to fiddle with java load paths so installation would be as simple as possible in commandbox.  I realize that this dependency probably excludes non-coldbox users from using it. 

Part of the reason why I used cbjavaloader is because in my lucee server tests, I kept getting the error "The OSGi Bundle with name [org.apache.pdfbox.app] is not available locally (C:\lucee\tomcat\lucee-server\bundles) or from the update provider (https://update.lucee.org)."  I'm guessing I don't have some Lucee extension enabled by default or something.

Adding cbjavaloader also broke all the tests. I'm not an expert at Testbox yet, but I *think* I have to move the tests into a "test-harness" folder so that I can use wirebox to create `PdfBox` and execute each test.

What are your thoughts on the cbjavaloader dependency?  Good idea? Bad idea?  Maybe there's a way to still use javaloader without requiring users to specify jar paths in the root application?

**Comment by mjclemente** [comment]
I'm willing to consider it, though my initial reaction is that I probably don't want to introduce another dependency (to keep it as simple as possible for those not using ColdBox as well). But maybe we can find a middle ground.

Could you open another issue to discuss this? And in it, can you explain how cbjavaloader makes it easier to use? Does it download the jars for you? Right now I'm not entirely understanding the friction. Thanks! 😀
